# Generated by Django 5.2.5 on 2025-09-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='features',
            field=models.JSONField(),
        ),
    ]
