# Generated by Django 5.2.5 on 2025-09-11 12:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_highlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Aditya Green Energies', help_text='Title for the About Us section', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description for the About Us section', null=True)),
                ('image', models.URLField(blank=True, help_text='URL of the image for About Us. If empty, a default image will be shown', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='highlight',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='main.about'),
            preserve_default=False,
        ),
    ]
