# Generated by Django 5.2.5 on 2025-09-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_about_highlight_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(blank=True, default='We are a trusted partner of Waaree Energies, delivering premium solar solutions in Bengaluru and beyond. Our mission is to empower homes and businesses with sustainable energy that saves money and protects the planet.', help_text='Description for the About Us section', null=True),
        ),
    ]
