# Generated by Django 5.2.5 on 2025-09-11 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_about_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Highlight',
        ),
    ]
