# Generated by Django 5.2.5 on 2025-09-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_highlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+91 9535156339', max_length=20)),
                ('email', models.EmailField(default='adityagreenenergies@gmail.com', max_length=254)),
                ('address', models.TextField(default='Sy No 184/4, Sarjapura Main Road, Dommasandra, Bengaluru, Karnataka, 562125')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
