# Generated by Django 5.2.5 on 2025-09-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_contactinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(default='+91 9535156339', max_length=100),
        ),
    ]
