# Generated by Django 5.2.5 on 2025-10-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_contactinfo_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinquiry',
            options={},
        ),
        migrations.RemoveField(
            model_name='contactinquiry',
            name='status',
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='electric_bill',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
